**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

# I. NumPy.

0. Імпортувати numpy загальноприйнятим способом.

In [ ]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [ ]:
merry_poppins_marks= [67, 87, 90, 74]
students_marks = np.array(merry_poppins_marks)
print("Merry Poppins marks:",students_marks)

Merry Poppins marks: [67 87 90 74]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [ ]:
prices= ([[54, 59, 50],[50, 55, 47],[59, 65, 53]])
stores_prices = np.array(prices)
print("Chocolate: Milk White Dark")
print("Silpo", stores_prices[0],"\nATB", stores_prices[1], "\nArsen", stores_prices[2])


Chocolate: Milk White Dark
Silpo [54 59 50] 
ATB [50 55 47] 
Arsen [59 65 53]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [ ]:
print(students_marks.dtype)
print(stores_prices.dtype)

int64
int64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [ ]:
print(students_marks.shape)
print(stores_prices.shape)

(4,)
(3, 3)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [ ]:
growing_profits = np.linspace(0, 1000.50, num=7)
print("Growing week`s profit:", growing_profits)

Growing week`s profit: [   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [ ]:
number_of_pillows = np.array([2, 2])
number_of_toys = np.array([4, 5])
vertical_array = np.vstack((number_of_pillows, number_of_toys))
horizontal_array = np.hstack((number_of_pillows, number_of_toys))
print(vertical_array, horizontal_array)

[[2 2]
 [4 5]] [2 2 4 5]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [ ]:
def transpose_distance(distance):
  """
  Takes array as input and transposes it

  Parameters
  ----------
  distance: array that will be transposed

  Returns
  -------
  transposed_distance: transposed products array
  """

  n, m = distance.shape

  transpose_distance = distance.reshape(m, n)

  return transpose_distance

if __name__ == "__main__":
  distance = np.array([[3,5,2,2],[54,654,123,543],[21,324,545,656]])
  transposed_distance = transpose_distance(distance)
  print(transposed_distance)


[[  3   5   2]
 [  2  54 654]
 [123 543  21]
 [324 545 656]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [ ]:
temperature_lviv = np.array([[2, 4, 8, 13], [23, 25, 20, 28], [23, 15, 34, 23], [35, 30, 28, 29], [30, 28, 33, 29]])
temperature_kyiv = np.array([[5, 7, 2, 5], [28, 27, 21, 24], [10, 13, 17, 6], [30, 28, 33, 29],[23, 25,33, 29]])

print("Addition:",temperature_lviv+temperature_kyiv)
print("\nSubtraction:",temperature_lviv-temperature_kyiv)
print("\nMultiplication by a number",temperature_lviv*4)
print("\nElement-wise multiplication operation:",temperature_lviv*temperature_kyiv)
print("\nMatrix multiplication:",np.dot(temperature_lviv,transpose_distance(temperature_kyiv)))


Addition: [[ 7 11 10 18]
 [51 52 41 52]
 [33 28 51 29]
 [65 58 61 58]
 [53 53 66 58]]

Subtraction: [[-3 -3  6  8]
 [-5 -2 -1  4]
 [13  2 17 17]
 [ 5  2 -5  0]
 [ 7  3  0  0]]

Multiplication by a number [[  8  16  32  52]
 [ 92 100  80 112]
 [ 92  60 136  92]
 [140 120 112 116]
 [120 112 132 116]]

Element-wise multiplication operation: [[  10   28   16   65]
 [ 644  675  420  672]
 [ 230  195  578  138]
 [1050  840  924  841]
 [ 690  700 1089  841]]

Matrix multiplication: [[ 631  445  665  703  749]
 [1942 1450 1946 1849 2441]
 [1765 1209 2001 1976 2628]
 [2302 1710 2355 2216 3135]
 [2308 1663 2447 2311 3134]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [ ]:
death_rate = np.array([[10,14,3,0,2],[23,27,59,12,24],[54,67,34,89,15]])

print(death_rate.min())
print(death_rate.max())
print(death_rate.sum())
print(death_rate.min(axis=1))
print(death_rate.max(axis=0))

0
89
433
[ 0 12 15]
[54 67 59 89 24]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [ ]:
day_flights = ([12,53,16,12,14,14,13,15,1])
print(np.unique(day_flights, return_counts=True))


(array([ 1, 12, 13, 14, 15, 16, 53]), array([1, 2, 1, 2, 1, 1, 1]))


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [ ]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [ ]:
patients_data = [
    {"Last Name": "Bloom", "First Name": "Orlando", "Date of Birth": "13-01-1977", "Body Weight": 77, "Medical Insurance": True},
    {"Last Name": "Cumberbatch", "First Name": "Benedict", "Date of Birth": "19-07-1976", "Body Weight": 80, "Medical Insurance": True},
    {"Last Name": "Rose", "First Name": "Lily", "Date of Birth": None, "Body Weight": 52, "Medical Insurance": False},
    {"Last Name": "Brown", "First Name": "Millie Bobby", "Date of Birth": "19-02-2004", "Body Weight": None, "Medical Insurance": False},
    {"Last Name": "Depp", "First Name": "Johnny", "Date of Birth": "09-06-1963", "Body Weight": 78, "Medical Insurance": True}
]

patients_table = pd.DataFrame(patients_data)

print(patients_table)
print(patients_table.dtypes)

     Last Name    First Name Date of Birth  Body Weight  Medical Insurance
0        Bloom       Orlando    13-01-1977         77.0               True
1  Cumberbatch      Benedict    19-07-1976         80.0               True
2         Rose          Lily          None         52.0              False
3        Brown  Millie Bobby    19-02-2004          NaN              False
4         Depp        Johnny    09-06-1963         78.0               True
Last Name             object
First Name            object
Date of Birth         object
Body Weight          float64
Medical Insurance       bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [ ]:
file_path = "/content/missile_attacks_daily.csv"

missle_attacks_table = pd.read_csv(file_path)

print(missle_attacks_table)

            time_start          time_end               model  \
0     2025-01-18 20:00  2025-01-19 09:00      Shahed-136/131   
1     2025-01-17 19:00  2025-01-18 08:00      Shahed-136/131   
2     2025-01-16 19:00  2025-01-17 09:00      Shahed-136/131   
3     2025-01-16 19:00  2025-01-17 09:00    Iskander-M/KN-23   
4     2025-01-16 19:00  2025-01-17 09:00          Iskander-M   
...                ...               ...                 ...   
2039  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2040        2022-09-30        2022-09-30            Orlan-10   
2041  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2042        2022-09-28        2022-09-28                X-59   
2043        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0         Bryansk oblast and Oryol oblast and Millerovo   
1     Primorsko-Akhtarsk and Bryansk oblast and Mill...   
2     Primorsko-Akhtarsk and Kursk oblast and Bryans..

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [ ]:
print(missle_attacks_table.head(10))

         time_start          time_end             model  \
0  2025-01-18 20:00  2025-01-19 09:00    Shahed-136/131   
1  2025-01-17 19:00  2025-01-18 08:00    Shahed-136/131   
2  2025-01-16 19:00  2025-01-17 09:00    Shahed-136/131   
3  2025-01-16 19:00  2025-01-17 09:00  Iskander-M/KN-23   
4  2025-01-16 19:00  2025-01-17 09:00        Iskander-M   
5  2025-01-15 20:00  2025-01-16 09:00    Shahed-136/131   
6  2025-01-15 06:00  2025-01-15 08:00         X-59/X-69   
7  2025-01-15 06:00  2025-01-15 08:00         X-22/X-32   
8  2025-01-15 06:00  2025-01-15 08:00       X-101/X-555   
9  2025-01-15 06:00  2025-01-15 08:00            Kalibr   

                                        launch_place       target  carrier  \
0      Bryansk oblast and Oryol oblast and Millerovo      Ukraine      NaN   
1  Primorsko-Akhtarsk and Bryansk oblast and Mill...      Ukraine      NaN   
2  Primorsko-Akhtarsk and Kursk oblast and Bryans...      Ukraine      NaN   
3                 Bryansk oblast and V

14. Отримайте інформацію про форму датафрейму.

In [ ]:
print(missle_attacks_table.shape)

(2044, 16)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [ ]:
print(missle_attacks_table.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2044 entries, 0 to 2043
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2044 non-null   object 
 1   time_end              2044 non-null   object 
 2   model                 2044 non-null   object 
 3   launch_place          1023 non-null   object 
 4   target                2016 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2041 non-null   float64
 7   destroyed             2044 non-null   int64  
 8   not_reach_goal        157 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           34 non-null     float64
 11  still_attacking       28 non-null     float64
 12  destroyed_details     294 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      object 
 15  source               

16. Отримайте статистику для колонок числового типу.

In [ ]:
print(missle_attacks_table.describe(include=[np.number]))

          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2041.000000  2044.000000      157.000000             32.000000   
mean     10.609995     7.491683       20.828025              2.312500   
std      21.041038    14.190972       19.877245              2.054696   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.000000              1.000000   
50%       2.000000     1.000000       16.000000              2.000000   
75%       9.000000     7.000000       30.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    34.000000        28.000000  
mean      2.000000         2.821429  
std       1.154701         2.931989  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         4.000000  
max       5.000000        10.000000  


17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [ ]:
unique_values = missle_attacks_table.nunique()
print(unique_values)

time_start               864
time_end                1015
model                     61
launch_place             135
target                    97
carrier                   58
launched                 113
destroyed                 81
not_reach_goal            55
cross_border_belarus       7
back_russia                5
still_attacking            8
destroyed_details        290
launched_details           4
launch_place_details       4
source                   960
dtype: int64


In [ ]:
print(unique_values.idxmin(), unique_values[unique_values.idxmin()])

launched_details 4


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Можливо б додала колонку з областями, які були таргетовані,я вважаю' буде легше візуалізувати та аналізувати дані пов'язані з областями.
2.   Є колонки в яких зовсім немає даних, тобто всі значення Nan або майже всі. Я вважаю це буде ускладнювати аналіз. Або змінити Nan значення на щось більш інформативне.
3. У датасеті присутні однакові значення в колонках, можливо їх б можна було об'єднати і в деяких рядках записати значення разом, щоб не перевіряти довше набір даних.
4. В колонці source велика кількість різних URL-посилань, тому не впевнена чи є сенс використовувати цю колонку в аналізі. Можливо записати ці джерела в іншому форматі, щоб можна було легко розуміти про що йде мова.





# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [ ]:
print(missle_attacks_table['launched'].astype(int))

0       61
1       39
2       50
3        4
4        2
        ..
2039     1
2040     3
2041     7
2042     5
2043     3
Name: launched, Length: 2044, dtype: int64


In [ ]:
missle_attacks_table['launched'] = missle_attacks_table['launched'].fillna(0)

20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [ ]:
print(missle_attacks_table.dropna(axis=1, thresh=0.3*len(missle_attacks_table)))

            time_start          time_end               model  \
0     2025-01-18 20:00  2025-01-19 09:00      Shahed-136/131   
1     2025-01-17 19:00  2025-01-18 08:00      Shahed-136/131   
2     2025-01-16 19:00  2025-01-17 09:00      Shahed-136/131   
3     2025-01-16 19:00  2025-01-17 09:00    Iskander-M/KN-23   
4     2025-01-16 19:00  2025-01-17 09:00          Iskander-M   
...                ...               ...                 ...   
2039  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2040        2022-09-30        2022-09-30            Orlan-10   
2041  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2042        2022-09-28        2022-09-28                X-59   
2043        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0         Bryansk oblast and Oryol oblast and Millerovo   
1     Primorsko-Akhtarsk and Bryansk oblast and Mill...   
2     Primorsko-Akhtarsk and Kursk oblast and Bryans..

21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [ ]:
missle_attacks_table_cleaned = missle_attacks_table.drop_duplicates()
missle_attacks_table_cleaned = missle_attacks_table_cleaned[missle_attacks_table_cleaned['time_start'] < missle_attacks_table_cleaned['time_end']]
missle_attacks_table_cleaned = missle_attacks_table_cleaned.reindex()
print(missle_attacks_table_cleaned)

number_of_removed_rows =  missle_attacks_table.shape[0] - missle_attacks_table_cleaned.shape[0]

print("Number of removed rows:",number_of_removed_rows)

            time_start          time_end             model  \
0     2025-01-18 20:00  2025-01-19 09:00    Shahed-136/131   
1     2025-01-17 19:00  2025-01-18 08:00    Shahed-136/131   
2     2025-01-16 19:00  2025-01-17 09:00    Shahed-136/131   
3     2025-01-16 19:00  2025-01-17 09:00  Iskander-M/KN-23   
4     2025-01-16 19:00  2025-01-17 09:00        Iskander-M   
...                ...               ...               ...   
2033  2022-10-06 09:00  2022-10-06 11:30         Mohajer-6   
2034        2022-10-06  2022-10-06 02:00    Shahed-136/131   
2037        2022-10-05  2022-10-05 02:00    Shahed-136/131   
2038  2022-10-02 00:00  2022-10-02 02:00    Shahed-136/131   
2041  2022-09-29 23:00  2022-09-29 23:59    Shahed-136/131   

                                           launch_place  \
0         Bryansk oblast and Oryol oblast and Millerovo   
1     Primorsko-Akhtarsk and Bryansk oblast and Mill...   
2     Primorsko-Akhtarsk and Kursk oblast and Bryans...   
3                  

**місце для текстової відповіді**

In [ ]:
840 рядків було видалено. Для перевірки я знайшла початкові розміри датафрейму і розміри очищеного, і відняла їхні значення.

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [13]:
print(missle_attacks_table[missle_attacks_table.isna().any(axis=1)])

            time_start          time_end               model  \
0     2025-01-18 20:00  2025-01-19 09:00      Shahed-136/131   
1     2025-01-17 19:00  2025-01-18 08:00      Shahed-136/131   
2     2025-01-16 19:00  2025-01-17 09:00      Shahed-136/131   
3     2025-01-16 19:00  2025-01-17 09:00    Iskander-M/KN-23   
4     2025-01-16 19:00  2025-01-17 09:00          Iskander-M   
...                ...               ...                 ...   
2039  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2040        2022-09-30        2022-09-30            Orlan-10   
2041  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2042        2022-09-28        2022-09-28                X-59   
2043        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0         Bryansk oblast and Oryol oblast and Millerovo   
1     Primorsko-Akhtarsk and Bryansk oblast and Mill...   
2     Primorsko-Akhtarsk and Kursk oblast and Bryans..